#!/usr/bin/env bash
# Stage a skill for publication to ClawHub.
#
#   bash tools/stage_release.sh <slug> [output-dir]
#
# Copies the files recorded in PROVENANCE.json under workingTree.files into a
# clean staging directory, re-verifies each one's SHA-256, and prints the
# publish command.
#
# Two files are held back from the upload:
#   README.md       repository-only documentation, never part of the package
#                   (already absent from workingTree.files)
#   skill-card.md   generated by ClawHub from the listing; it cannot be
#                   published directly, so it is kept in the repo as part of
#                   the verified package record but excluded from the upload
#
# This script does NOT publish. It stages and verifies; you run the publish.

set -uo pipefail
cd "$(dirname "$0")/.." || exit 2

SLUG="${1:-}"
OUT="${2:-dist/$SLUG}"

if [ -z "$SLUG" ]; then
  echo "usage: $0 <slug> [output-dir]" >&2
  echo "  slugs: tencent-andon, cmg" >&2
  exit 2
fi

SRC="skills/$SLUG"
if [ ! -d "$SRC" ]; then
  echo "error: no such skill directory: $SRC" >&2
  exit 2
fi

VERSION=$(python3 -c "
import json,sys
d=json.load(open('PROVENANCE.json'))
for s in d['skills']:
    if s['slug']=='$SLUG':
        print(s['workingTree']['version']); sys.exit(0)
sys.exit(1)
") || { echo "error: $SLUG not found in PROVENANCE.json" >&2; exit 2; }

echo "Staging $SLUG v$VERSION -> $OUT"
echo

rm -rf "$OUT"
mkdir -p "$OUT"

# Copy and verify each recorded file.
if ! python3 - "$SLUG" "$SRC" "$OUT" <<'PY'
import hashlib, json, pathlib, shutil, sys

slug, src, out = sys.argv[1], pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3])
entry = next(s for s in json.load(open("PROVENANCE.json"))["skills"] if s["slug"] == slug)

# Generated by ClawHub from the listing; cannot be uploaded as package content.
UPLOAD_EXCLUDED = {"skill-card.md"}

bad = 0
staged = 0
for f in entry["workingTree"]["files"]:
    if f["path"] in UPLOAD_EXCLUDED:
        print(f"  skip           (ClawHub-generated)  {f['path']}")
        continue
    s = src / f["path"]
    if not s.is_file():
        print(f"  MISSING  {f['path']}")
        bad += 1
        continue
    data = s.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != f["sha256"] or len(data) != f["size"]:
        print(f"  MISMATCH {f['path']}")
        bad += 1
        continue
    d = out / f["path"]
    d.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(s, d)
    staged += 1
    print(f"  ok  {len(data):>7} B  {f['path']}")

if bad:
    print(f"\n{bad} file(s) failed verification — nothing staged.")
    sys.exit(1)
print(f"\n{staged} file(s) staged and verified.")
PY
then
  rm -rf "$OUT"
  exit 1
fi

# Nothing credential-shaped should reach the registry.
echo
echo "Re-scanning staged output..."
if grep -rInE 'AKID[A-Za-z0-9]{16,}|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----' "$OUT" >/dev/null 2>&1; then
  echo "  FAIL: credential material found in staged output" >&2
  exit 1
fi
if grep -rInE 'http://[A-Za-z0-9]' "$OUT" | grep -vE '127\.0\.0\.1|localhost|\[::1\]' >/dev/null 2>&1; then
  echo "  FAIL: plaintext http:// endpoint in staged output" >&2
  grep -rInE 'http://[A-Za-z0-9]' "$OUT" | grep -vE '127\.0\.0\.1|localhost|\[::1\]' >&2
  exit 1
fi
echo "  clean"

CHANGELOG_TEXT=$(python3 -c "
import json
d=json.load(open('PROVENANCE.json'))
e=next(s for s in d['skills'] if s['slug']=='$SLUG')
print(e['workingTree']['note'])
")

echo
echo "==============================================================="
echo "Staged: $OUT"
echo
echo "Publish with:"
echo
echo "  clawhub login          # once, if not already authenticated"
echo "  clawhub whoami         # confirm you are llm-pm"
echo
echo "  clawhub skill publish $OUT \\"
echo "    --slug $SLUG \\"
echo "    --owner llm-pm \\"
echo "    --version $VERSION \\"
echo "    --changelog \"<release notes>\""
echo
echo "Suggested changelog source: CHANGELOG.md, section [$VERSION]"
echo "  ($CHANGELOG_TEXT)"
echo
echo "After publishing, confirm the new scan verdict:"
echo
echo "  curl -s https://clawhub.ai/api/v1/skills/$SLUG/versions/$VERSION \\"
echo "    | python3 -m json.tool | grep -A6 '\"security\"'"
echo "==============================================================="
